require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'lib/tasks/**/*'

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 30

Layout/LineLength:
  Max: 120

Style/ClassAndModuleChildren:
  EnforcedStyle: nested

RSpec/ExampleLength:
  Max: 10

RSpec/MultipleExpectations:
  Max: 1

RSpec/NestedGroups:
  Max: 4

Rails/SkipsModelValidations:
  Exclude:
    - 'spec/**/*'

Rails/HttpStatus:
  EnforcedStyle: symbolic

Rails/FilePath:
  EnforcedStyle: arguments

Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test
    - staging
